#Gera o arquivo objeto do double_hashing
all:
	@echo 'Compilando double_hashing...'
	gcc double_hashing.c -o double_hashing

#Remove possíveis arquivos objetos criados
clean:
	@echo 'Limpando arquivos compilados...'
	rm -f *.o
	rm -f double_hashing
	rm -f *.output
